### ISSUE TITLE
SQS event null in maven build 1.4.3

### ISSUE THREAD

**Issue by imshashank** [epsagon/epsagon-java#43]
Hi,

I just upgraded to build 1.4.3 and I am having a new issue. In one of my lambda the trigger is a SQS Event and that event is now coming up as null.

When I removed Epsagon then everything worked back again.

This is the handlerequest->
```
public Void handleRequest(SQSEvent sqsEvent, Context context) {
```

I used ObjectMapper to see what was being received as sqsevent and epsagon was somehow making it null. This is a new error and was only introduced in 1.4.3

**Comment by galbash** [comment]
should be fixed by #45 , will note here when it's merged.

**Comment by galbash** [comment]
version 1.4.4 is now released, please let me know if it fixes your issue

**Comment by imshashank** [comment]
I plan to deploy next week, will let u know.

**Comment by galbash** [comment]
ok, closing it in the meantime, feel free to re-open if the issue is not resolved
